export type Priority = 'S' | 'A' | 'B' | 'C' | string;

export type MasterRule = {
  master_version?: string;
  rule_id: string;
  brand_id: string;
  category_id: string;
  カテゴリ: string;
  性別?: string;
  ブランド: string;
  ブランド日本語?: string;
  服種類: string;
  '商品名・狙い目': string;
  季節?: string;
  季節ピーク?: string;
  想定販売期間?: string;
  素材加点?: string;
  素材タグ?: string;
  サイズ加点?: string;
  サイズタグ?: string;
  仕入れ上限?: string;
  仕入れ上限_min?: string;
  仕入れ上限_max?: string;
  想定販売価格?: string;
  想定販売価格_min?: string;
  想定販売価格_max?: string;
  粗利目安?: string;
  粗利_min?: string;
  粗利_max?: string;
  想定送料_min?: string;
  想定送料_max?: string;
  配送サイズ?: string;
  送料注意度?: string;
  優先度: Priority;
  ブランドスコア?: string;
  ジャンルスコア?: string;
  素材スコア?: string;
  サイズスコア?: string;
  回転見込み?: string;
  回転スコア?: string;
  利益見込み?: string;
  偽物リスク?: string;
  真贋リスクスコア?: string;
  劣化リスク?: string;
  状態リスクスコア?: string;
  相場信頼度?: string;
  総合スコア_初期?: string;
  推奨判定_初期?: string;
  データ信頼度?: string;
  強い条件?: string;
  強みタグ?: string;
  需要タグ?: string;
  避ける条件?: string;
  状態NGタグ?: string;
  リスクタグ?: string;
  検索キーワード?: string;
  最低確認相場数?: string;
  写真必須箇所?: string;
  現場アクション?: string;
  AI判定メモ?: string;
  アプリ入力必須項目?: string;
  即見送り条件?: string;
  例外条件?: string;
  AI追加質問?: string;
  メルカリ検索式1?: string;
  メルカリ検索式2?: string;
  メルカリ検索式3?: string;
  メルカリ検索URL1?: string;
  メルカリ検索URL2?: string;
  メルカリ検索URL3?: string;
  撮影指示詳細?: string;
  購入制御ルール?: string;
};

export type ProductInput = {
  brand: string;
  category: string;
  itemType: string;
  size: string;
  material: string;
  condition: string;
  purchasePrice: number;
  expectedShipping?: number;
  soldCompsCount: number;
  hasTag: boolean;
  hasDamage: boolean;
  hasSmell: boolean;
  authenticityUnclear: boolean;
  purchaseLocation: string;
};

export type JudgeResult = {
  matchedRule?: MasterRule;
  score: number;
  decision: '買い' | '条件付き買い' | '慎重' | '見送り';
  estimatedSaleMin: number;
  estimatedSaleMax: number;
  estimatedProfitMin: number;
  estimatedProfitMax: number;
  suggestedMaxBuy?: number;
  reasons: string[];
  warnings: string[];
  nextActions: string[];
};
